---
title: "Datafest"
author: "Drew, Richard, Anmol, Meredith, An"
date: 2023-4-7
output:
  github_document:
    toc: true
---

# Question

# Setup

<!-- ----------------------------------------------------------------------- -->

```{r setup}
library(tidyverse)
```

# Download Data

```{r}
attorneys <- read_csv("./data/attorneys.csv")
summary(attorneys)
attorneyTimeEntries <- read_csv("./data/attorneytimeentries.csv")
summary(attorneyTimeEntries)
categories <- read_csv("./data/categories.csv")
summary(categories)
clients <- read_csv("./data/clients.csv")
summary(clients)
questionPosts <- read_csv("./data/questionposts.csv")
summary(questionPosts)
questions <- read_csv("./data/questions.csv")
summary(questions)
stateSites <- read_csv("./data/statesites.csv")
summary(stateSites)
subcategories <- read_csv("./data/subcategories.csv")
summary(subcategories)

```

# Explore Data

```{r}
glimpse(categories)
categories %>% 
ggplot(aes(x=Category)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))

glimpse(subcategories)
subcategories %>% 
  add_count(Subcategory, name = "Count") %>% 
  arrange(desc(Count)) %>% 
  top_n( n=10, Count) %>%
  
  ggplot(aes(x=Subcategory)) + 
  geom_bar() +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
```

# Data Cleaning

```{r q1-task}
## TODO: Give the filename for your copy of Table B01003

```
